version: '3'
services:
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: "$PGUSER"
      POSTGRES_PASSWORD: "$PGPASSWORD"
#      volumes:
#        - db:/var/lib/postgresql/data:z
    ports:
      - "25432:5432"
  pentaho:
    build: .
    environment:
      PGHOST: "$PGHOST"
      PGPORT: "$PGPORT"
      PGDATABASE: "$PGDATABASE"
      PGUSER: "$PGUSER"
      PGPASSWORD: "$PGPASSWORD"
    ports:
      - "18080:8080"

volumes:
    db:
